### ISSUE TITLE
cargo install fails

### ISSUE THREAD

**Issue by fabh2o** [RedL0tus/VanityGPG#4]
Installing via cargo (`cargo install vanity_gpg`) (vanity_gpg v0.3.0, not the latest version) result in an error: `error[E0432]: unresolved import 'clap::Clap'`
Installing directly from the repo (version 0.3.1) works fine: `cargo install --git https://github.com/RedL0tus/VanityGPG.git`
I think that the cargo package must be updated to the latest version.

**Comment by RedL0tus** [comment]
I've just published [`v0.3.2`](https://crates.io/crates/vanity_gpg/0.3.2), please check it out. It should work fine now.

**Comment by RedL0tus** [comment]
LOL it's actually fixed first in v0.3.1, but I forgot to publish that to crates.io 🤣

**Comment by fabh2o** [comment]
It now installs fine. Thank you!
